# Generated by Django 5.0.7 on 2024-07-24 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_level', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='weatherData',
        ),
    ]
