# Generated by Django 5.0.7 on 2024-07-24 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_level', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='weather_data',
        ),
    ]
