# Generated by Django 5.0.7 on 2024-07-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_level', '0007_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='weather_data',
            new_name='weather_model',
        ),
    ]
