# Generated by Django 5.0.7 on 2024-07-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_level', '0008_rename_weather_data_weather_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('dominant_weather_condition', models.CharField(max_length=250)),
            ],
        ),
    ]
