# Generated by Django 5.0.7 on 2024-07-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_level', '0009_daily_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='daily_summary',
        ),
    ]
