# Generated by Django 5.0.7 on 2024-07-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_level', '0011_daily_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='daily_summary',
            new_name='DailySummary',
        ),
    ]
